In [1]:
import numpy as np

In [2]:
a = np.array([2.0, 3.0, 5.0])
a

array([2., 3., 5.])

In [3]:
a.dtype

dtype('float64')

In [4]:
a = np.array([2.0, 3.0, 5.0], "float32")
a

array([2., 3., 5.], dtype=float32)

In [5]:
np.random.randn(10)

array([-0.29292464,  0.18972149, -2.60973051, -1.55098479, -1.42945784,
        0.3395906 ,  0.53949771, -0.61627471, -0.66097852,  0.24602652])

In [8]:
np.array([1.0, 1, "v"]).dtype

dtype('<U32')

In [33]:
np.random.seed(1)
np.random.randn(10)

array([ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763,
       -2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038])

In [34]:
np.random.seed(1)
np.random.ranf(10)

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
       3.96767474e-01, 5.38816734e-01])

In [36]:
a = np.array([1, 2, 8, 3])
a + 3

array([ 4,  5, 11,  6])

In [37]:
a * 3

array([ 3,  6, 24,  9])

In [38]:
a / 3

array([0.33333333, 0.66666667, 2.66666667, 1.        ])

In [39]:
a ** 2

array([ 1,  4, 64,  9])

In [42]:
%%time 

n = 1000 ** 2
a = np.random.ranf(n)
print(np.mean(a**2))

0.333256547851886
CPU times: user 17.1 ms, sys: 983 µs, total: 18.1 ms
Wall time: 12.7 ms


In [43]:


import random

In [45]:
%%time 
b = 0
for _ in range(n):
    b += random.random() ** 2
print(b/n)

0.33302141340122526
CPU times: user 180 ms, sys: 1.21 ms, total: 181 ms
Wall time: 180 ms


In [46]:
a = np.array([
    [2, 3, 4],
    [-1, 1, 1],
    [23, 4, 5],
    [4, 9, 0]
])

In [47]:
a[0]

array([2, 3, 4])

In [48]:
a[:, 0]

array([ 2, -1, 23,  4])

In [49]:
np.diagonal(a)

array([2, 1, 5])

In [50]:
a[:3, :]

array([[ 2,  3,  4],
       [-1,  1,  1],
       [23,  4,  5]])

In [51]:
np.abs(a)

array([[ 2,  3,  4],
       [ 1,  1,  1],
       [23,  4,  5],
       [ 4,  9,  0]])

In [52]:
a[[0, 1]]

array([[ 2,  3,  4],
       [-1,  1,  1]])

In [53]:
a[:, [0, 1]]

array([[ 2,  3],
       [-1,  1],
       [23,  4],
       [ 4,  9]])

In [54]:
a[[0, 0]]

array([[2, 3, 4],
       [2, 3, 4]])

In [63]:
a[[0, 0, 1, 1, 2, 2, 10]]

IndexError: index 10 is out of bounds for axis 0 with size 4

In [64]:
a[:2, :]

array([[ 2,  3,  4],
       [-1,  1,  1]])

In [65]:
a[:20, :]

array([[ 2,  3,  4],
       [-1,  1,  1],
       [23,  4,  5],
       [ 4,  9,  0]])

In [66]:
a[0, 0]

2

In [67]:
a

array([[ 2,  3,  4],
       [-1,  1,  1],
       [23,  4,  5],
       [ 4,  9,  0]])

In [69]:
b = np.array([9, 3, 1])
a.dot(b)

array([ 31,  -5, 224,  63])

In [70]:
b.shape

(3,)

In [71]:
b = b.reshape((1, -1))

In [72]:
b.shape

(1, 3)

In [73]:
a.dot(b)

ValueError: shapes (4,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [74]:
a.dot(b.T)

array([[ 31],
       [ -5],
       [224],
       [ 63]])